# Python Data Science Handbook
## Author: VanderPlas, Jacob T

Utilizing this book as a guide for some Python libraries


In [3]:
# Creating Arrays from list

import numpy as np

a = np.array([1,4,2,5,3]) # Int

b = np.array([3.14,4,2,3])

print(type(a[1]))
print(type(b[1]))

# Nested lists for multidimensional array
n = np.array([range(i,i+3) for i in [2,4,6]])

n

<class 'numpy.int64'>
<class 'numpy.float64'>


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
# Creating Arrays from Scratch

# Array filled with zeros
a = np.zeros(10, dtype=int)

# A 3x5 floating-point array filled with 1s
b = np.ones((3,5), dtype=float)

# Array filled with a linear sequence
c = np.arange(0,20,2)

# Array of five values evenly spaced
d = np.linspace(0,1,5)

# A 3x3 array of uniformly distributed random values 
# between 0 and 1
e = np.random.random((3,3))

# A 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
f = np.random.normal(0,1,(3,3))

# A 3x3 identity matrix
g = np.eye(3)


print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# NumPy Array Attributes

# seed used for reproducibility of the data
np.random.seed(0)

# One-dimensional array
x1 = np.random.randint(10, size = 6)

# Two-dimensional array
x2 = np.random.randint(10, size = (3,4))

# Three-dimensional array
x3 = np.random.randint(10, size = (3,4,5))

print("x3 ndim:",x3.ndim)       # Dimension of the array
print("x3 shape:",x3.shape)     # Size of each dimension
print("x3 size:",x3.size)       # Total size of the array

# Obtaing the data type of the array
print("dtype:",x3.dtype)

# Size, in bytes, of each array element
print("itemsize:",x3.itemsize,"bytes")

# Size, in bytes, of the total array
print("nbytes:",x3.nbytes,"bytes")


x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [23]:
# Array Indexing

# Negative indices index from the end of the array
print(x1[-1])
print(x1[-2])

# Accesssing multidimensional array using comma-separated
# tuple of indices
print(x2[0,0])
print(x2[2,0])

# Modifying values
x2[0,0] = 12
print(x2[0,0])

# OBS: Numpy arrays and Python lists are different
# NumPy arrays have a fixed type
# That means all components of the array will be of
# the same datatype


9
7
3
1
12
