# Python data science handbook
## Author: VanderPlas, Jacob T

Utilizing this book as a guide for some Python libraries


In [10]:
# Creating Arrays from list

import numpy as np

a = np.array([1,4,2,5,3]) # Int

b = np.array([3.14,4,2,3])

print(type(a[1]))
print(type(b[1]))

# Nested lists for multidimensional array
n = np.array([range(i,i+3) for i in [2,4,6]])

n

<class 'numpy.int64'>
<class 'numpy.float64'>


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [23]:
# Creating Arrays from Scratch

# Array filled with zeros
a = np.zeros(10, dtype=int)

# A 3x5 floating-point array filled with 1s
b = np.ones((3,5), dtype=float)

# Array filled with a linear sequence
c = np.arange(0,20,2)

# Array of five values evenly spaced
d = np.linspace(0,1,5)

# A 3x3 array of uniformly distributed random values 
# between 0 and 1
e = np.random.random((3,3))

# A 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
f = np.random.normal(0,1,(3,3))

# A 3x3 identity matrix
g = np.eye(3)


print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
